_data :
  data_root: /data10T/data/wujipeng/ec/data/static/
  class: utils.dataset.ec.ECDataset
  settings:
    vocab_root: /data10T/data/wujipeng/ec/data/raw_data
    batch_size: 16

_model :
  model_root : /data10T/data/wujipeng/ec/model/
  name : han_v3_w2v_200d
  class: models.han.han.HierarchicalAttentionNetworkV3
  settings :
    word_model:
      class: WordAttention
      args:
        vocab_size: 23070
        embedding_dim: 200
        batch_size: 16
        sequence_length: 41
        rnn_size: 200
        rnn_layers: 1
        dropout: 0.5
    sentence_model:
      class: SentenceWithPosition
      args:
        batch_size: 16
        word_rnn_size: 200
        rnn_size: 200
        rnn_layers: 1
        pos_size: 103
        pos_embedding_dim: 200
        pos_embedding_file: /data10T/data/wujipeng/ec/data/embedding/pos_embedding200d.pkl
        dropout: 0.5
        fix_pos: True
    vocab_size: 23070
    num_classes: 2
    embedding_dim: 200
    dropout: 0.5
    fix_embed: False

_train :
  debug_level: 0 # 0: 用test数据 1: 重新分配数据
  gpu: 3
  criterion :
    class : torch.nn.CrossEntropyLoss
    args :
      reduction : mean
      ignore_index: -100
  clip_grad_norm : True
  grad_clip_value : 0.5
  optimizer :
    class : torch.optim.Adam
    embedding:
      lr: 1.e-5
    args :
      lr : 3.e-4
      betas: [0.9, 0.999]
      eps: 1.e-8
  pretrain : True
  pretrained_file : /data10T/data/wujipeng/ec/data/embedding/w2v_200d.pkl
  max_epoch : 100
  batch_size : 16
  early_stopping_rounds : 10
#  decay_round: 3
#  decay_rate: 0.5
  disp_freq : 15
  eval_freq : 119
  save_freq : 119
  finetune: False
#  finetune_round: 3
  metrics:
    class: metrics.ec.ec.ECMetrics
    args:
      ignore_index: -100
  statistics:
    class: statistics.ec.ec.ECStatistics

_eval :
  eval_root: /data10T/data/wujipeng/ec/eval/
  debug_level: 1 # 0: 用test数据 1: 重新分配数据
  batch_size : 16
  metrics:
    class: metrics.ec.ec.ECMetrics
    args:
      ignore_index: -100
  criterion:
    class: torch.nn.CrossEntropyLoss
    args:
      reduction: mean
      ignore_index: -100
  statistics:
    class: statistics.ec.ec.ECStatistics