_data :
  data_root: /data/wujipeng/ec/data/static/
  class: utils.dataset.ec.ECDataset
  settings:
    vocab_root: /data/wujipeng/ec/data/raw_data
    batch_size: 16

_model :
  model_root : /data/wujipeng/ec/model/hcn
  model_class: models.han.hcn.HierarchicalConvolutionNetwork
  model_name : hcn
  settings :
    batch_size: 16
    vocab_size: 23071
    position_size: 102
    num_classes: 2
    sequence_length: 41
    embedding_dim: 300
    pos_embedding_dim: 300
    num_features: 200
    sentence_dim: 300
    kernel_sizes: [2, 3, 4]
    sentence_rnn_size: 100
    sentence_rnn_layers: 1
    dropout: 0.3
    fix_embed: False

_train :
  criterion :
    class : torch.nn.CrossEntropyLoss
    args :
      reduction : mean
      ignore_index: -100
  clip_grad_norm : False
  grad_clip_value : 1
  optimizer :
    class : torch.optim.Adam
    args :
      lr : 1.e-3
      betas: [0.9, 0.999]
      eps: 1.e-8
  pretrain : True
  pretrained_file : /data/wujipeng/ec/data/embedding/sogou_embedding300d.pkl
  max_epoch : 100
  batch_size : 16
  early_stopping_rounds : 5
  disp_freq : 15
  eval_freq : 119
  save_freq : 119
  finetune: True
  metrics:
    class: metrics.ec.ec.ECMetrics
    args:
      ignore_index: -100
  statistics:
    class: statistics.ec.ec.ECStatistics

_eval :
  batch_size : 16
  metrics :
    class : metrics.ec.han.ECAMetrics
    settings :
      average : binary
      ignore_index: -100
  statistics :
    class : statistics.ec.ec.ECAStatistics
    settings :
      real_file : /home/wujipeng/data/ec/data/real.npz
